---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: siibra-api-prod-ebrains
spec:
  commonName: siibra-api.apps.ebrains.eu
  isCA: false
  dnsNames:
  - siibra-api.apps.ebrains.eu
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-production-issuer-1
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  renewBefore: 120h
  secretName: siibra-api-prod-ebrains-secret
  usages:
  - server auth
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: siibra-api-rc-ebrains
spec:
  commonName: siibra-api-rc.apps.ebrains.eu
  isCA: false
  dnsNames:
  - siibra-api-rc.apps.ebrains.eu
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-production-issuer-1
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  renewBefore: 120h
  secretName: siibra-api-rc-ebrains-secret
  usages:
  - server auth
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: siibra-api-prod-ebrains-alt
spec:
  commonName: siibra-atlases.apps.ebrains.eu
  isCA: false
  dnsNames:
  - siibra-atlases.apps.ebrains.eu
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-production-issuer-1
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  renewBefore: 120h
  secretName: siibra-api-prod-ebrains-alt-secret
  usages:
  - server auth
