apiVersion: v1
kind: Secret
metadata:
  name: kubectl-config
type: Opaque
data:
  config: |
    YXBpVmVyc2lvbjogdjEKa2luZDogQ29uZmlnCmNsdXN0ZXJzOgotIGNsdXN0ZXI6CiAgICBzZXJ2
    ZXI6IGh0dHBzOi8vcmFuY2hlci50Yy5odW1hbmJyYWlucHJvamVjdC5ldS9rOHMvY2x1c3RlcnMv
    Yy1tLWpjeDJxaHFuCiAgbmFtZTogcmtlMi0xLWpzY2Nsb3VkCmNvbnRleHRzOgotIGNvbnRleHQ6
    CiAgICBjbHVzdGVyOiBya2UyLTEtanNjY2xvdWQKICAgIG5hbWVzcGFjZTogc2lpYnJhLWFwaQog
    ICAgdXNlcjogcmtlMi0xLWpzY2Nsb3VkCiAgbmFtZTogZWIyLXNhcGkKY3VycmVudC1jb250ZXh0
    OiBlYjItc2FwaQpwcmVmZXJlbmNlczoge30KdXNlcnM6Ci0gbmFtZTogcmtlMi0xLWpzY2Nsb3Vk
    CiAgdXNlcjoKICAgIHRva2VuOiBmb28tYmFyCg==
