apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    type: longhorn-pvc
  name: data-volume-claim
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: longhorn-1
