---
apiVersion: v1
kind: Service
metadata:
  name: siibra-api-v1
  labels:
    deprecated: foo
spec:
  selector:
    app: siibra-api-v1
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: siibra-api-v2
  labels:
    deprecated: foo
spec:
  selector:
    app: siibra-api-v2
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: siibra-api-v1
  labels:
    deprecated: foo
spec:
  selector:
    matchLabels:
      app: siibra-api-v1
  template:
    metadata:
      labels:
        app: siibra-api-v1
    spec:
      containers:
      - name: siibra-api-v1
        envFrom:
        - secretRef:
            name: siibra-api-deprec-secret
        - configMapRef:
            name: siibra-api-deprec-configmap
        image: docker-registry.ebrains.eu/siibra/siibra-api:0.1.16
        resources:
          limits:
            memory: "1Gi"
            cpu: "500m"
          requests:
            memory: "1Gi"
            cpu: "500m"
        ports:
        - containerPort: 5000
          protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: siibra-api-v2
  labels:
    deprecated: foo
spec:
  selector:
    matchLabels:
      app: siibra-api-v2
  template:
    metadata:
      labels:
        app: siibra-api-v2
    spec:
      containers:
      - name: siibra-api-v2
        envFrom:
        - secretRef:
            name: siibra-api-deprec-secret
        - configMapRef:
            name: siibra-api-deprec-configmap
        image: docker-registry.ebrains.eu/siibra/siibra-api:0.2.3
        resources:
          limits:
            memory: "2Gi"
            cpu: "500m"
          requests:
            memory: "2Gi"
            cpu: "500m"
        ports:
        - containerPort: 5000
          protocol: TCP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: siibra-api-deprec-configmap
  labels:
    deprecated: foo
data:
  SIIBRA_REDIS_SERVICE_HOST: cache-redis-service
