apiVersion: v1
kind: Pod
metadata:
  labels:
    app: warmup-pod
  name: warmup-pod
spec:
  containers:
  - name: warmup-container
    image: docker-registry.ebrains.eu/siibra/siibra-api:rc-worker-v4
    imagePullPolicy: Always
    command:
    - python
    args:
    - -m
    - new_api.run_warmup
    resources:
      limits:
        cpu: "2"
        memory: 4Gi
      requests:
        cpu: "2"
        memory: 1Gi
    volumeMounts:
    - mountPath: /siibra-api-volume
      name: data-volume
    env:
    - name: SIIBRA_CACHEDIR
      value: "$SIIBRA_CACHEDIR"
    - name: SKIP_CACHEINIT_MAINTENANCE
      value: "1"
  restartPolicy: Never
  volumes:
  - name: data-volume
    persistentVolumeClaim:
      claimName: data-volume-claim
