apiVersion: v1
kind: Pod
metadata:
  labels:
    app: warmup-pod
  name: warmup-pod
spec:
  containers:
  - name: warmup-container
    image: docker-registry.ebrains.eu/siibra/siibra-api:rc-worker
    imagePullPolicy: Always
    command:
    - python
    args:
    - -c
    - import siibra; siibra.cache.clear(); siibra.warm_cache(999)
    resources:
      limits:
        cpu: 900m
        memory: 1Gi
      requests:
        cpu: 500m
        memory: 1Gi
    volumeMounts:
    - mountPath: /siibra-api-volume
      name: data-volume
    env:
    - name: SIIBRA_CACHEDIR
      value: "$SIIBRA_CACHEDIR"
    - name: SKIP_CACHEINIT_MAINTENANCE
      value: "1"
  restartPolicy: Never
  volumes:
  - name: data-volume
    persistentVolumeClaim:
      claimName: data-volume-claim
