version: '3'
services:

  redis:
    image: redis
    restart: always

  siibra-api:
    depends_on:
    - redis
    image: siibra-api:v0.4-all
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - '5000:5000'
    environment:
      SIIBRA_API_ROLE: all
      REDIS_HOST: redis
      REDIS_PORT: '6379'
