version: '3'
services:

  redis:
    image: redis
    restart: always

  siibra-api:
    depends_on:
    - redis
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - '5000:5000'
    environment:
      REDIS_HOST: redis
      REDIS_PORT: '6379'
