version: '3'
services:

  redis:
    image: redis:latest
    restart: always

  siibra-api:
    depends_on:
    - redis
    image: docker-registry.ebrains.eu/siibra/siibra-api:${SIIBRA_API_IMAGE_VERSION}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - '5000:5000'
    environment:
      SIIBRA_API_ROLE: all
      REDIS_HOST: redis
      REDIS_PORT: '6379'
