version: '3'
services:
  app:
    container_name: siibra-api
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
    - ./:/app
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - SIIBRA_ENVIRONMENT=${SIIBRA_ENVIRONMENT}
      - EBRAINS_IAM_CLIENT_ID=${EBRAINS_IAM_CLIENT_ID}
      - EBRAINS_IAM_CLIENT_SECRET=${EBRAINS_IAM_CLIENT_SECRET}
      - EBRAINS_IAM_REFRESH_TOKEN=${EBRAINS_IAM_REFRESH_TOKEN}
