version: '3'
services:

  redis:
    image: redis
    restart: always

  siibra-api:
    depends_on:
    - redis
    volumes:
      - ./:/api
      - ./siibra-cache:/siibra-cache
    entrypoint: "uvicorn api.server:api --host 0.0.0.0 --port 5000 --workers 4 --reload"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - '5000:5000'
    environment:
      REDIS_HOST: redis
      REDIS_PORT: '6379'
      SIIBRA_CACHEDIR: /siibra-cache
