apiVersion: v1
kind: Template
metadata:
  name: siibra-api-branch-deploy-v2
  annotations:
    description: "Deploy branch of siibra-api"
    tags: "python,fastapi,siibra-api"
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: siibra-api-branch-deploy-v2-${DEPLOY_FLAVOUR}
    labels:
      app: siibra-api-branch-deploy-v2-${DEPLOY_FLAVOUR}
  spec:
    replicas: 3
    revisionHistoryLimit: 10
    selector:
      deploymentconfig: siibra-api-branch-deploy-v2-${DEPLOY_FLAVOUR}
    template:
      metadata:
        labels:
          app: siibra-api-branch-deploy
          deploymentconfig: siibra-api-branch-deploy-v2-${DEPLOY_FLAVOUR}
      spec:
        containers:
        - env:
          - name: SESSION_SECRET
            value: ${SESSION_SECRET}
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                key: database-password
                name: siibra-redis
          - name: EBRAINS_IAM_CLIENT_ID
            valueFrom: 
              configMapKeyRef:
                name: hbp-oauth-config-map
                key: HBP_CLIENTID
          - name: EBRAINS_IAM_CLIENT_SECRET
            valueFrom: 
              configMapKeyRef:
                name: hbp-oauth-config-map
                key: HBP_CLIENTSECRET
          - name: EBRAINS_IAM_REFRESH_TOKEN
            valueFrom: 
              configMapKeyRef:
                name: hbp-oauth-config-map
                key: REFRESH_TOKEN
                
          envFrom:
          - configMapRef:
              name: siibra-config-overwrite
            prefix: SIIBRA_CONFIG_

          # this is sucky
          # in future, either change siibra-python to use diskcache/rediscache
          # or use startupProbe (openshift 4.4+) to allow >600 sec container startup time
          livenessProbe:
            failureThreshold: 10
            exec:
              command:
              - pytest
              - ./e2e_tests/
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          readinessProbe:
            failureThreshold: 10
            exec:
              command:
              - pytest
              - ./e2e_tests/
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10

          image: "docker-registry.ebrains.eu/siibra/siibra-api:${DOCKER_IMAGE_TAG}"
          imagePullPolicy: Always
          name: siibra-api-${DEPLOY_FLAVOUR}
          ports:
          - containerPort: 5000
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: siibra-api-branch-deploy-v2-${DEPLOY_FLAVOUR}
    name: siibra-api-branch-deploy-v2-${DEPLOY_FLAVOUR}
  spec:
    ports:
    - name: 5000-tcp
      port: 5000
      protocol: TCP
      targetPort: 5000
    selector:
      deploymentconfig: siibra-api-branch-deploy-v2-${DEPLOY_FLAVOUR}
    type: ClusterIP
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: siibra-api-branch-deploy-v2-${DEPLOY_FLAVOUR}
    name: siibra-api-branch-deploy-v2-${DEPLOY_FLAVOUR}
  spec:
    host: siibra-api-${DEPLOY_FLAVOUR}.apps${DEPLOY_SITE_POSTFIX}.hbp.eu
    port:
      targetPort: 5000-tcp
    tls:
      insecureEdgeTerminationPolicy: Redirect
      termination: edge
    to:
      kind: Service
      name: siibra-api-branch-deploy-v2-${DEPLOY_FLAVOUR}
      weight: 100
    wildcardPolicy: None

parameters:
- description: Session secret
  from: '[A-Z0-9]{16}'
  generate: expression
  name: SESSION_SECRET
- name: DOCKER_IMAGE_TAG
  required: true
- name: DEPLOY_FLAVOUR
  required: true
  description: |
    A lot of routing/naming follow special rules:
    - does not allow special characters, except for - or . .
    - only allows lower case.
    valid values are: stable | rc | latest
- name: DEPLOY_SITE_POSTFIX
  description: |
    Where to deploy. Valid values are: '-dev'
  value: ''

labels:
  template: siibra-api-branch-deploy-template-v2
