apiVersion: v1
kind: Template
metadata:
  name: siibra-toolbox-deploy-template
  annotations:
    description: "Deploy siibra toolbox"
    tags: "python,async"
objects:

# worker deployment config
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: siibra-toolbox-deploy-${TOOLBOX_NAME}-worker
    labels:
      app: siibra-toolbox-deploy-${TOOLBOX_NAME}
      app_role: worker
  spec:
    replicas: 3
    revisionHistoryLimit: 10
    selector:
      deploymentconfig: siibra-toolbox-deploy-${TOOLBOX_NAME}-worker
    template:
      metadata:
        labels:
          app: siibra-toolbox-deploy-${TOOLBOX_NAME}
          deploymentconfig: siibra-toolbox-deploy-${TOOLBOX_NAME}-worker
          app_role: worker
      spec:
        containers:
        - env:
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                key: database-password
                name: redis
          - name: SIIBRA_TOOLBOX_NAME
            value: ${SIIBRA_TOOLBOX_NAME}
          - name: SIIBRA_TOOLBOX_DATA_DIR
            value: ${SHARED_VOLUME_MOUNT}
          - name: SIIBRA_TOOLBOX_LOG_DIR
            value: ${LOG_VOLUME_MOUNT}

          image: ${TOOLBOX_WORKER_IMAGE}
          imagePullPolicy: Always
          name: siibra-toolbox-deploy-${TOOLBOX_NAME}-worker
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /siibra_toolbox/http_wrapper/conf
              name: volume-${CELERY_CONFIG_WORKER_VOLUME_NAME}
              readOnly: true
            - mountPath: ${SHARED_VOLUME_MOUNT}
              name: volume-${SHARED_VOLUME_WORKER_VOLUME_NAME}
            - mountPath: ${LOG_VOLUME_MOUNT}
              name: volume-${LOG_VOLUME_WORKER_VOLUME_NAME}

        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
          - configMap:
              defaultMode: 420
              name: celery-config
            name: volume-${CELERY_CONFIG_WORKER_VOLUME_NAME}
          - name: volume-${SHARED_VOLUME_WORKER_VOLUME_NAME}
            persistentVolumeClaim:
              claimName: toolbox-storage
          - name: volume-${LOG_VOLUME_WORKER_VOLUME_NAME}
            persistentVolumeClaim:
              claimName: log-volume

# server deployment config
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: siibra-toolbox-deploy-${TOOLBOX_NAME}-server
    labels:
      app: siibra-toolbox-deploy-${TOOLBOX_NAME}
      app_role: server
  spec:
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      deploymentconfig: siibra-toolbox-deploy-${TOOLBOX_NAME}-server
    template:
      metadata:
        labels:
          app: siibra-toolbox-deploy-${TOOLBOX_NAME}
          deploymentconfig: siibra-toolbox-deploy-${TOOLBOX_NAME}-server
          app_role: server
      spec:
        containers:
        - env:
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                key: database-password
                name: redis
          - name: SIIBRA_TOOLBOX_NAME
            value: ${SIIBRA_TOOLBOX_NAME}
          - name: SIIBRA_TOOLBOX_DATA_DIR
            value: ${SHARED_VOLUME_MOUNT}
          - name: SIIBRA_TOOLBOX_LOG_DIR
            value: ${LOG_VOLUME_MOUNT}

          image: ${TOOLBOX_SERVER_IMAGE}
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /ready
              port: 6001
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /ready
              port: 6001
              scheme: HTTP
            initialDelaySeconds: 3
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 6
          name: siibra-toolbox-deploy-${TOOLBOX_NAME}-server
          ports:
          - containerPort: 6001
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File

          volumeMounts:
            - mountPath: /siibra_toolbox/http_wrapper/conf
              name: volume-${CELERY_CONFIG_SERVER_VOLUME_NAME}
              readOnly: true
            - mountPath: ${SHARED_VOLUME_MOUNT}
              name: volume-${SHARED_VOLUME_SERVER_VOLUME_NAME}
            - mountPath: ${LOG_VOLUME_MOUNT}
              name: volume-${LOG_VOLUME_SERVER_VOLUME_NAME}

        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
          - configMap:
              defaultMode: 420
              name: celery-config
            name: volume-${CELERY_CONFIG_SERVER_VOLUME_NAME}
          - name: volume-${SHARED_VOLUME_SERVER_VOLUME_NAME}
            persistentVolumeClaim:
              claimName: toolbox-storage
          - name: volume-${LOG_VOLUME_SERVER_VOLUME_NAME}
            persistentVolumeClaim:
              claimName: log-volume

# route-pod
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: siibra-toolbox-deploy-${TOOLBOX_NAME}
    name: siibra-toolbox-deploy-${TOOLBOX_NAME}-service
  spec:
    ports:
    - name: 6001-tcp
      port: 6001
      protocol: TCP
      targetPort: 6001
    selector:
      deploymentconfig: siibra-toolbox-deploy-${TOOLBOX_NAME}-server
    type: ClusterIP

# route
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: siibra-toolbox-deploy-${TOOLBOX_NAME}
    name: siibra-toolbox-deploy-${TOOLBOX_NAME}-route
  spec:
    host: ${TOOLBOX_ROUTE}
    port:
      targetPort: 6001-tcp
    tls:
      insecureEdgeTerminationPolicy: Redirect
      termination: edge
    to:
      kind: Service
      name: siibra-toolbox-deploy-${TOOLBOX_NAME}-service
      weight: 100
    wildcardPolicy: None

parameters:
- name: TOOLBOX_NAME
  description: Toolbox name
  required: true
- name: TOOLBOX_ROUTE
  description: Toolbox Route, without scheme (i.e. no https?://). should be [a-z0-9][a-z0-9-][a-z0-9].apps(-dev)?.hbp.eu
  required: true
- name: TOOLBOX_WORKER_IMAGE
  description: Docker image for the worker
  required: true
- name: TOOLBOX_SERVER_IMAGE
  description: Docker image for the server
  required: true


- name: CELERY_CONFIG_SERVER_VOLUME_NAME
  description: Randomly generated volume name. Do not overwrite
  from: '[a-z0-9]{8}'
  generate: expression
- name: CELERY_CONFIG_WORKER_VOLUME_NAME
  description: Randomly generated volume name. Do not overwrite
  from: '[a-z0-9]{8}'
  generate: expression

  # RESULT VOLUME
- name: SHARED_VOLUME_SERVER_VOLUME_NAME
  description: Randomly generated volume name. Do not overwrite
  from: '[a-z0-9]{8}'
  generate: expression
- name: SHARED_VOLUME_WORKER_VOLUME_NAME
  description: Randomly generated volume name. Do not overwrite
  from: '[a-z0-9]{8}'
  generate: expression
- name: LOG_VOLUME_SERVER_VOLUME_NAME
  description: Randomly generated volume name. Do not overwrite
  from: '[a-z0-9]{8}'
  generate: expression
- name: SHARED_VOLUME_MOUNT
  description: Path where shared volume will be mounted. Applies to both server and worker pods.
  value: /siibra_toolbox_volume

  # LOG VOLUME
- name: LOG_VOLUME_WORKER_VOLUME_NAME
  description: Randomly generated volume name. Do not overwrite
  from: '[a-z0-9]{8}'
  generate: expression
- name: LOG_VOLUME_SERVER_VOLUME_NAME
  description: Randomly generated volume name. Do not overwrite
  from: '[a-z0-9]{8}'
  generate: expression
- name: LOG_VOLUME_MOUNT
  description: Path where shared volume will be mounted. Applies to both server and worker pods.
  value: /siibra_toolbox_logs

labels:
  template: siibra-toolbox-deploy-template

# prerequisite:
# - named persistent volume named `toolbox-storage`
# - named persistent volume named `log-volume`
# - redis secret at secretKeyRef.redis.database-password
# - configMap.celery-config -> volume mounted to /siibra_toolbox/http_wrapper/conf (celery config)
# - redis instance, reachable via config in configMap.celery-config.celeryconfig