apiVersion: v1
kind: Template
metadata:
  name: siibra-api-v5-server-template
  annotations:
    description: "Deploy siibra api server"
    tags: "siibra-api"
objects:

- apiVersion: v1
  kind: Service
  metadata:
    labels:
      flavor: ${FLAVOR}
      app: siibra-api
      template_version: v5
      app_role: server
    name: siibra-api-service-${FLAVOR}
  spec:
    ports:
    - name: 5000-tcp
      port: 5000
      protocol: TCP
      targetPort: 5000
    selector:
      app: siibra-api
      flavor: ${FLAVOR}
      app_role: server
    type: ClusterIP

- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: siibra-api-server-${FLAVOR}
    labels:
      flavor: ${FLAVOR}
      app: siibra-api
      template_version: v5
      app_role: server
  spec:
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      deploymentconfig: siibra-api-server-${FLAVOR}
    template:
      metadata:
        labels:
          flavor: ${FLAVOR}
          app: siibra-api
          deploymentconfig: siibra-api-server-${FLAVOR}
          template_version: v5
          app_role: server
      spec:
        containers:
        - env:
          - name: SIIBRA_CACHEDIR
            value: ${SHARED_VOLUME_MOUNT}
          - name: SIIBRA_API_LOG_DIR
            value: ${LOG_VOLUME_MOUNT}
          - name: SIIBRA_API_NAMESPACE
            value: siibraapi${FLAVOR}
          envFrom:
          - configMapRef:
              name: siibra-api-config
            prefix: SIIBRA_API_

          image: ${SIIBRA_API_SERVER_IMAGE}

          imagePullPolicy: Always
          name: server-${CONTAINER_NAME}
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: ${SHARED_VOLUME_MOUNT}
              name: volume-${SHARED_VOLUME_WORKER_VOLUME_NAME}
            - mountPath: ${LOG_VOLUME_MOUNT}
              name: volume-${LOG_VOLUME_WORKER_VOLUME_NAME}

        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
          - name: volume-${SHARED_VOLUME_WORKER_VOLUME_NAME}
            persistentVolumeClaim:
              claimName: siibra-shared-storage-2
          - name: volume-${LOG_VOLUME_WORKER_VOLUME_NAME}
            persistentVolumeClaim:
              claimName: log-volume

parameters:
- name: SIIBRA_API_SERVER_IMAGE
  description: Docker image for the worker
  required: true
- name: LOG_VOLUME_WORKER_VOLUME_NAME
  description: Randomly generated volume name. Do not overwrite
  from: '[a-z0-9]{8}'
  generate: expression
- name: SHARED_VOLUME_WORKER_VOLUME_NAME
  description: Randomly generated volume name. Do not overwrite
  from: '[a-z0-9]{8}'
  generate: expression
- name: SHARED_VOLUME_MOUNT
  description: Path where shared volume will be mounted. Applies to both server and worker pods.
  value: /siibra-api-volume
- name: LOG_VOLUME_MOUNT
  description: Path where log volume will be mounted. Applies to both server and worker pods.
  value: /siibra_api_logs
- name: CONTAINER_NAME
  description: Name of container. If not supplied, will be autogenerated.
  from: '[a-z0-9]{8}'
  generate: expression
- name: FLAVOR
  description: Flavor of deployments. (e.g. latest,rc,stable)
  value: latest
  required: true
