apiVersion: v1
kind: Template
metadata:
  name: siibra-api-v5-template
  annotations:
    description: "Deploy siibra api"
    tags: "siibra-api"
objects:

- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: siibra-api-deploy-${FLAVOR}-worker-q-${SIIBRA_API_QUEUE}
    labels:
      app: siibra-api-deploy-${FLAVOR}
      queue: ${SIIBRA_API_QUEUE}
      app_role: worker
  spec:
    replicas: 3
    revisionHistoryLimit: 10
    selector:
      deploymentconfig: siibra-api-deploy-worker
    template:
      metadata:
        labels:
          app: siibra-api-deploy-${FLAVOR}
          deploymentconfig: siibra-api-deploy-worker
          queue: ${SIIBRA_API_QUEUE}
          app_role: worker
      spec:
        containers:
        - env:
          - name: SIIBRA_CACHEDIR
            value: ${SHARED_VOLUME_MOUNT}
          - name: SIIBRA_API_LOG_DIR
            value: ${LOG_VOLUME_MOUNT}
          envFrom:
          - configMapRef:
              name: siibra-api-config
            prefix: SIIBRA_API_

          image: ${SIIBRA_API_WORKER_IMAGE}
          args:
          - -Q
          - ${SIIBRA_API_QUEUE}

          imagePullPolicy: Always
          name: siibra-api-deploy-${FLAVOR}-worker
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: ${SHARED_VOLUME_MOUNT}
              name: volume-${SHARED_VOLUME_WORKER_VOLUME_NAME}
            - mountPath: ${LOG_VOLUME_MOUNT}
              name: volume-${LOG_VOLUME_WORKER_VOLUME_NAME}

        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
          - name: volume-${SHARED_VOLUME_WORKER_VOLUME_NAME}
            persistentVolumeClaim:
              claimName: siibra-shared-storage-2
          - name: volume-${LOG_VOLUME_WORKER_VOLUME_NAME}
            persistentVolumeClaim:
              claimName: log-volume

parameters:
- name: FLAVOR
  description: Flavor of siibra-api (e.g. stable, rc, latest, etc)
  required: true
- name: SIIBRA_API_WORKER_IMAGE
  description: Docker image for the worker
  required: true
- name: SIIBRA_API_QUEUE
  description: Queue for the worker to join.
  value: celery
  required: true
