apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sapi-cdn-cert
spec:
  secretName: sapi-cdn-cert-secret
  renewBefore: 120h 
  commonName: siibra-api-cdn.apps.dev-adacloud.ebrains.eu
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
  - server auth
  dnsNames:
  # (CHANGE ME! same as `commonName`)
  - siibra-api-cdn.apps.dev-adacloud.ebrains.eu
  issuerRef:
    name: letsencrypt-production-issuer-1
    kind: ClusterIssuer 
---
apiVersion: v1
data: 
  SKIP_CACHEINIT_MAINTENANCE: "1"
  SIIBRA_API_LOG_DIR: /siibra_api_logs
  REDIS_HOST: cache-redis-service
  SIIBRA_API_REMAP_PROVIDERS: |
    https://object.cscs.ch/v1/AUTH_08c08f9f119744cbbf77e216988da3eb::https://siibra-cdn.examcopedia.club/dp-eb-eu/api/v1/buckets/reference-atlas-data/imgsvc
    https://neuroglancer.humanbrainproject.eu::https://siibra-cdn.examcopedia.club/ng-hbp-eu
    https://data-proxy.ebrains.eu::https://siibra-cdn.examcopedia.club/dp-eb-eu

kind: ConfigMap
metadata:
  name: sapi-cdn-configmap
