name: "[deploy] on helm (v4)"

on:
  workflow_call:
    inputs:
      DEPLOYMENT_NAME:
        required: true
        type: string
        
      HELM_FILE:
        default: ".helm/siibra-api-v4-worker"
        type: string
      
      FALVOR:
        required: true
        type: string
      
      QUEUE:
        required: true
        type: string

      IMAGE_TAG:
        default: "0.3-worker"
        type: string
      
      RESOURCE:
        default: "low" # high
        type: string

      WORKER_PATH:
        default: "api.worker.app"
        type: string
      
      PULL_POLICY:
        default: IfNotPresent
        type: string

    secrets:
      KUBECONFIG:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: './.github/workflows/composite-set-k8s-cred'
      with:
        secrets: ${{ secrets.KUBECONFIG }}
    - name: 'Get status'
      run: |
        helm status ${{ inputs.DEPLOYMENT_NAME }}
        HELM_STATUS=$(echo $?)
        echo "HELM_STATUS: $HELM_STATUS"
        echo "HELM_STATUS=$HELM_STATUS" >> $GITHUB_ENV
        
    - name: Set Vars
      run: |
        SAPI_VERSION=$(cat VERSION)
        
        echo "SAPI_VERSION: $SAPI_VERSION"

        if [[ -z "$SAPI_VERSION" ]]
        then
          echo "SAPI_VERSION cannot be found $SAPI_VERSION"
          exit 1
        fi
        
        echo "SAPI_VERSION=$SAPI_VERSION" >> $GITHUB_ENV
    
    - name: Run deploy
      run: |
        if [[ "$HELM_STATUS" == "0" ]]
        then
          helm upgrade \
            --set sapi.version=$SAPI_VERSION \
            --set sapi.flavor=${{ inputs.FALVOR }} \
            --set sapi.queue=${{ inputs.QUEUE }} \
            --set image.tag=${{ inputs.IMAGE_TAG }} \
            --set image.pullPolicy=${{ input.PULL_POLICY }} \
            --set sapi.worker=${{ inputs.WORKER_PATH }} \
            --set sapi.resources.flavor=${{ inputs.RESOURCE }} \
            --reuse-values \
            --history-max 1 \
            ${{ inputs.DEPLOYMENT_NAME }} \
            ${{ inputs.HELM_FILE }}
        else 
          helm install \
            --set sapi.version=$SAPI_VERSION \
            --set sapi.flavor=${{ inputs.FALVOR }} \
            --set sapi.queue=${{ inputs.QUEUE }} \
            --set image.tag=${{ inputs.IMAGE_TAG }} \
            --set image.pullPolicy=${{ input.PULL_POLICY }} \
            --set sapi.worker=${{ inputs.WORKER_PATH }} \
            --set sapi.resources.flavor=${{ inputs.RESOURCE }} \
            ${{ inputs.DEPLOYMENT_NAME }} \
            ${{ inputs.HELM_FILE }}
        fi
