name: '[docker image prod]'

on:
  release:
    types:
    - published

env:
  OKD_PROJECT: siibra-api
  OKD_ENDPOINT: https://okd.hbp.eu:443
  OKD_SECRET: ${{ secrets.OKD_PROD_SECRET }}
  DOCKER_REGISTRY: 'docker-registry.ebrains.eu/siibra/'
  DOCKER_IMG: 'siibra-api'

jobs:
  build-docker-img:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: 'Build & Push versioned tag to registry'
      run: |
        echo "Login to docker registry"
        docker login \
          -u '${{ secrets.EBRAINS_DOCKER_REG_USER }}' \
          -p '${{ secrets.EBRAINS_DOCKER_REG_TOKEN }}' \
          docker-registry.ebrains.eu

        VERSION=$(grep -Po '^__version__.*?"\K[\w.]+' app/__init__.py)
        VERSIONED_DOCKERTAG=${{ env.DOCKER_REGISTRY }}${{ env.DOCKER_IMG }}:$VERSION

        echo "Building $VERSIONED_DOCKERTAG"
        docker build \
          -t $VERSIONED_DOCKERTAG \
          .
        docker push $VERSIONED_DOCKERTAG
        
        echo "Done"
